name: docker-build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag qwertmax/jenkins-with-docker:$(date +%s)

    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: qwertmax/jenkins-with-docker
      with:
        name: qwertmax/jenkins-with-docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
