name: docker-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
    - uses: actions/checkout@master
      run: docker build . --file Dockerfile --tag qwertmax/jenkins-with-docker:1.0

    - name: Publish to Registry
    - uses: actions/checkout@master
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push the Docker image to the registry
      run: docker push qwertmax/jenkins-with-docker:1.0
